version: '3.7'

services:
  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - WHITELIST=10.10.0.*
      - PEERPORT=51413
    volumes:
      - ${TransmissionFolder}/config:/config
      - ${TransmissionFolder}/downloads:/downloads
      - ${TransmissionFolder}/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
    restart: unless-stopped

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

volumes:
  portainer_data:
