version: '3.7'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - PLEX_CLAIM=${PLEXCLAIM}
      - HOSTNAME=${PLEXHOSTNAME}
    volumes:
      - ${PLEXLOCATION}/config:/config
      - ${PLEXLOCATION}/transcode:/transcode
      - ${PLEXMOVIES}:/media/movies
      - ${PLEXMUSIC}:/media/music
      - ${PLEXTVSHOWS}:/media/tvshows
      - ${PLEXVIDEOS}:/media/videos
    restart: unless-stopped

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

volumes:
  portainer_data:
